version: '3.8'
services:
  device-configuration:
    build:
      context: .
      dockerfile: modules/device-configuration/Dockerfile
    expose:
      - 4000
    env_file:
      - .env
    restart: always    

  data-reception:
    build:
      context: .
      dockerfile: modules/data-reception/Dockerfile
    expose:
      - 4001
    env_file:
      - .env
    restart: always

  data-processing:
    build:
      context: .
      dockerfile: modules/data-processing/Dockerfile
    expose:
      - 4002
    env_file:
      - .env
    restart: always

  threshold-validator:
    build:
      context: .
      dockerfile: modules/threshold-validator/Dockerfile
    expose:
      - 4003
    env_file:
      - .env
    restart: always