version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-server
    ports:
      - "1888:1888"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf