version: '3.8'
services:
  postgresql:
    image: postgres:alpine3.20
    container_name: postgres-db
    ports: 
      - "5440:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - background
    env_file:
      - .env
    restart: always

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto-server
    ports:
      - "1888:1888"
      - "8888:8888"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs:/mosquitto/config/certs
    networks:
      - background
    restart: always
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - background
    env_file:
      - .env
    restart: always      
    
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    networks:
      - background
    env_file:
      - .env
    restart: always

  sbc-configuration:
    build:
      context: .
      dockerfile: go-modules/sbc-configuration/Dockerfile
    container_name: sbc-configuration-service
    ports:
      - "4000:4000"
    depends_on:
      - kafka
    networks:
      - background
    env_file:
      - .env
    restart: always    

  data-reception:
    build:
      context: .
      dockerfile: go-modules/data-reception/Dockerfile
    container_name: data-reception-service
    ports:
      - "4001:4001"
    depends_on:
      - mosquitto
    networks:
      - background
    env_file:
      - .env
    restart: always

networks:
  background:
    driver: bridge

volumes:
  postgres-db: