version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-server
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf