version: '3.8'
services:
  device-configuration:
    build:
      context: .
      dockerfile: modules/device-configuration/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: always    

  data-reception:
    build:
      context: .
      dockerfile: modules/data-reception/Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - .env
    restart: always

  data-processing:
    build:
      context: .
      dockerfile: modules/data-processing/Dockerfile
    ports:
      - "4002:4002"
    env_file:
      - .env
    restart: always