CREATE TABLE DEVICES (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) UNIQUE,
    DESCRIPTION VARCHAR(100),
    ACTIVE BOOLEAN DEFAULT TRUE -- TRUE significa activo, FALSE significa inactivo
);

CREATE TABLE UPDATE_TYPES (
    ID_TYPE VARCHAR(255) PRIMARY KEY,
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE DEVICE_UPDATES (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    HASH_UPDATE VARCHAR(255),
    ID_TYPE VARCHAR(255) REFERENCES UPDATE_TYPES(ID_TYPE),
    CREATION_DATETIME_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATETIME_UTC TIMESTAMP,
    CONSTRAINT UNIQUE_HASH_UPDATE UNIQUE (ID_DEVICE, HASH_UPDATE)
);

CREATE TABLE PARAMETERS (
    ID_PARAMETER VARCHAR(255) PRIMARY KEY,
    DEFAULT_PERIOD INT,
    TABLE_POINTER VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    HAS_THRESHOLD BOOLEAN DEFAULT FALSE,
    THRESHOLD_COLUMN_NAME VARCHAR(255) NULL,
    DEFAULT_THRESHOLD_VALUE FLOAT NULL
);

CREATE TABLE DEVICE_READING_SETTINGS (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    PARAMETER VARCHAR(255) REFERENCES PARAMETERS(ID_PARAMETER),
    PERIOD INT,
    ACTIVE BOOLEAN DEFAULT TRUE, -- TRUE significa activo, FALSE significa inactivo
    THRESHOLD_VALUE FLOAT NULL
);

CREATE TABLE MAIN_DEVICE_INFORMATION (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    HOSTNAME VARCHAR(255),
    PROCESSOR VARCHAR(255),
    RAM VARCHAR(255),
    HOSTID VARCHAR(255),
    OS VARCHAR(255),
    KERNEL VARCHAR(255),
    CPU_COUNT INT,
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RAM_USAGE (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    TOTAL_RAM BIGINT,
    FREE_RAM BIGINT,
    USED_RAM BIGINT,
    USED_PERCENT_RAM DECIMAL(5, 2),
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DISK_USAGE (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    DISK_NAME VARCHAR(255),
    TOTAL_DISK BIGINT,
    FREE_DISK BIGINT,
    USED_DISK BIGINT,
    USED_PERCENT_DISK DECIMAL(5, 2),
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NETWORK_STATS (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    INTERFACE_NAME VARCHAR(255),
    BYTES_SENT BIGINT,
    BYTES_RECV BIGINT,
    PACKETS_SENT BIGINT,
    PACKETS_RECV BIGINT,
    ERROUT BIGINT,
    ERRIN BIGINT,
    DROPIN BIGINT,
    DROPOUT BIGINT,
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NETWORK_INFORMATION (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    INTERFACE_NAME VARCHAR(255),
    MTU INT,
    HARDWARE_ADDR VARCHAR(255),
    FLAGS VARCHAR(255),
    ADDRS VARCHAR(255),
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CPU_TEMPERATURE (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    SENSOR_KEY VARCHAR(255),
    TEMPERATURE DECIMAL(5, 2),
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UPTIME (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    UPTIME_MINUTES INT,
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LAST_REBOOT (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    LAST_REBOOT TIMESTAMP,
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CPU_USAGE (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    CPU_USAGE DECIMAL(5, 2),
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LOAD_AVERAGE (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    LOAD_AVERAGE_1M DECIMAL(5, 2),
    LOAD_AVERAGE_5M DECIMAL(5, 2),
    LOAD_AVERAGE_15M DECIMAL(5, 2),
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ROLES (
    ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(100)
);

CREATE TABLE PERMISSIONS (
    ID SERIAL PRIMARY KEY,
    PERMISSION_NAME VARCHAR(50) NOT NULL UNIQUE,
    ICON VARCHAR(100),
    PATH VARCHAR(100),
    DESCRIPTION VARCHAR(100)
);

CREATE TABLE ROLE_PERMISSIONS (
    ID_ROLE INT REFERENCES ROLES(ID) ON DELETE CASCADE,
    ID_PERMISSION INT REFERENCES PERMISSIONS(ID) ON DELETE CASCADE,
    PRIMARY KEY (ID_ROLE, ID_PERMISSION)
);


CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    ACTIVE BOOLEAN DEFAULT TRUE,
    ID_ROLE INT REFERENCES ROLES(ID),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- DEFAULT DATA
INSERT INTO PARAMETERS (ID_PARAMETER, DEFAULT_PERIOD, TABLE_POINTER, DESCRIPTION, HAS_THRESHOLD, THRESHOLD_COLUMN_NAME, DEFAULT_THRESHOLD_VALUE) VALUES
('main_info', 3600, 'MAIN_DEVICE_INFORMATION', 'Información principal del dispositivo', FALSE, NULL, NULL),
('ram', 30, 'RAM_USAGE', 'Uso de RAM', TRUE, 'USED_PERCENT_RAM', 70),
('disk', 3600, 'DISK_USAGE', 'Uso de disco', TRUE, 'USED_PERCENT_DISK', 60),
('net_stats', 180, 'NETWORK_STATS', 'Estadísticas de red', FALSE, NULL, NULL),
('net_info', 600, 'NETWORK_INFORMATION', 'Información de red', FALSE, NULL, NULL),
('cpu_temp', 30, 'CPU_TEMPERATURE', 'Temperatura de la CPU', TRUE, 'TEMPERATURE', 42),
('uptime', 300, 'UPTIME', 'Tiempo en línea', FALSE, NULL, NULL),
('last_reboot', 1800, 'LAST_REBOOT', 'Último reinicio del dispositivo', FALSE, NULL, NULL),
('cpu_usage', 30, 'CPU_USAGE', 'Uso de CPU', TRUE, 'CPU_USAGE', 75),
('load_average', 60, 'LOAD_AVERAGE', 'Promedio de carga', FALSE, 'LOAD_AVERAGE_5M', 1.5);

INSERT INTO UPDATE_TYPES (ID_TYPE, DESCRIPTION) VALUES
('startup', 'Inicialización del dispositivo'),
('update', 'Actualización del dispositivo');

INSERT INTO ROLES (ROLE_NAME, DESCRIPTION)
VALUES
    ('admin', 'Administrator with full permissions'),
    ('supervisor', 'Supervisor with limited permissions'),
    ('viewer', 'Viewer with read-only permissions');

INSERT INTO PERMISSIONS (PERMISSION_NAME, ICON, PATH, DESCRIPTION)
VALUES
    ('devices', 'hardware-chip-outline', '/devices', 'Dispositivos'),
    ('users', 'people-outline', '/users', 'Usuarios'),
    ('dashboard', 'bar-chart-outline', '/dashboard', 'Dashboard');

INSERT INTO ROLE_PERMISSIONS (ID_ROLE, ID_PERMISSION)
VALUES
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='admin'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='devices')),
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='admin'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='users')),
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='admin'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='dashboard')),
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='supervisor'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='devices')),
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='supervisor'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='dashboard')),
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='viewer'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='dashboard'));

INSERT INTO USERS (USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, ID_ROLE)
VALUES ('jperez', 'jperez@ceiot.lse', '$2b$10$apMib6tAp91D42jWTtx1ROBLF1xTvgS1Za8LaH0MOkMAODAdYOWeK', 'jose', 'perez', (SELECT ID FROM ROLES WHERE ROLE_NAME='admin'))